### DISCUSSION TITLE
Provide Static Binaries using Github Actions

### DISCUSSION THREAD

**Discussion by Azathothas** [owasp-noir/noir#185] [Ideas]
As per the readme: https://github.com/hahwul/noir#from-sources
```bash
# Install Crystal-lang
# https://crystal-lang.org/install/

# Clone this repo
git clone https://github.com/hahwul/noir
cd noir

# Install Dependencies
shards install

# Build
shards build --release --no-debug

# Copy binary
cp ./bin/noir /usr/bin/
```

I hardly know anything about crystal lang, but can't we use Gihub actions to auto release static binaries?
Maybe something like this:

```YAML
name: Build Static noir Binaries

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"  

env:
  # https://i.redd.it/o6xypg00uac91.png
  USER_AGENT: "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/115.0.5790.160 Mobile/15E148 Safari/604.1"
  GITHUB_TOKEN: ${{ secrets.STATIC_NOIR_RELEASER }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:        
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
          
      - name: Check Version
        id: check_version
        run: |
          # Get latest version
          export VERSION=$(curl -qfsSL "https://api.github.com/repos/hahwul/noir/releases/latest" | jq -r '.tag_name' )
          # If we get rate-limited, git clone the repo
          if [ -z "$VERSION" ]; then
            cd $(mktemp -d) && git clone https://github.com/hahwul/noir && cd noir
            export VERSION=$(git tag --sort=-creatordate | head -n 1)
          fi
          # Export it to ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          # Get stored version
          export STORED_VERSION=$(cat $GITHUB_WORKSPACE/main/noir/version.txt)
          if [ "$VERSION" == "$STORED_VERSION" ]; then
            echo "Version $VERSION is already Fetched & Updated"
            echo "versions_same=true" >> $GITHUB_ENV
          else
            echo "Fetching... --> $VERSION (from <-- $STORED_VERSION)"
            echo "versions_same=false" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Compare Versions
        if: env.versions_same != 'true'
        run: |
          # Update version.txt with the latest version
          echo $VERSION > $GITHUB_WORKSPACE/main/noir/version.txt
          echo "Updated version.txt with the latest version $VERSION"

      - name: Download Latest Source Code (Github_API)
        if: env.versions_same != 'true'
        run: |
          # Get latest Source Code
          curl -qfLJ $(curl -qfsSL "https://api.github.com/repos/hahwul/noir/releases/latest" | jq -r '.zipball_url') -o "$HOME/noir.zip"     
        continue-on-error: true

      - name: Clone repository if curl fails and zip
        if: env.versions_same != 'true'
        run: |
          if [ ! -f "$HOME/noir.zip" ]; then
            cd $HOME && git clone https://github.com/hahwul/noir.git && cd noir && git checkout "$VERSION"
            zip -ro "$HOME/noir.zip" "$HOME/noir" 
          fi
        continue-on-error: false
        
      - name: Install CoreUtils
        if: env.versions_same != 'true'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends bison build-essential ca-certificates flex file jq pkg-config qemu-user-static wget 
        continue-on-error: false 

      - name: Install Crystal
        if: env.versions_same != 'true'
        run: |
          #https://crystal-lang.org/install/on_ubuntu/
          curl -fsSL https://crystal-lang.org/install.sh | sudo bash
        continue-on-error: false 

   #Linux
      - name: Build noir for x86_64-unknown-linux-gnu
        if: env.versions_same != 'true'
        run: |
          #Get the zip
          cd $(mktemp -d) && cp "$HOME/noir.zip" .
          find . -type f -name '*.zip*' -exec unzip -o {} \;
          cd $(find . -maxdepth 1 -type d | grep -v '^.$')
          # Build
          shards install
          shards build --release --no-debug --production --static
          # Strip & Metadata
          strip "./bin/noir"
          file "./bin/noir" && ldd "./bin/noir" ; sha256sum "./bin/noir"
          # Prepare Release
          mkdir -p "/tmp/releases/"
          cp "./bin/noir" "/tmp/releases/noir-x86_64-unknown-linux-gnu"
          # Tar it
          tar -czvf noir-x86_64-unknown-linux-gnu.tar.gz -C ./bin noir
          cp "./noir-x86_64-unknown-linux-gnu.tar.gz" "/tmp/releases"
        continue-on-error: false 

  #Create a new Release & Publish
  # Repo: https://github.com/softprops/action-gh-release
  # Market-Place: https://github.com/marketplace/actions/gh-release
      - name: Releaser
        if: env.versions_same != 'true'
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: "noir ${{ env.VERSION }}"
          tag_name: "noir_${{ env.VERSION }}"
          prerelease: false
          draft: false
          generate_release_notes: false
          token: "${{ secrets.GITHUB_TOKEN }}"          
          body: |
            `Changelog`: _https://github.com/hahwul/noir/releases/tag/${{ env.VERSION }}_
          files: |
            /tmp/releases/*
```
