### ISSUE TITLE
Spec of Tagger Rule

### ISSUE THREAD

**Issue by hahwul** [owasp-noir/noir#396]
For #316 #317

```yaml
id: Rule ID
info:
  name: 
  author: 
  severity: critical
  description: 
  reference:
    - https://www.hahwul.com
  tags: oauth,ssrf

type: (line/file/all)
matchers-condition: and
matchers: 
    - type: regex
      value: /..../
    - type: string
      value: abcd..
```
