### ISSUE TITLE
Add Passive Scan

### ISSUE THREAD

**Issue by hahwul** [owasp-noir/noir#419]
Passive Scan is a feature in Noir that allows for the collection of various issues and information during the analysis of source code by using specified rules. It uses a YAML-defined file and collects information based on defined regular expressions during the source code analysis, displaying the results. During this process, any data that can be mapped to an endpoint is mapped and shown.

> Add a new function by combining #316 #317 #319 issues.

## Flags

* `-p` `--use-passive-scan`
* `--passive-scan-rules`

## Scan remote rule directory: 
`$NOIR_HOME/passive_scans` e.g`~/.config/noir/passive_scans`

## Scan rule Format (YAML)
```yaml
id: ...
info:
  name: ABCD
  author:
    - alice
    - bob
  severity: critical
  description: ....
  reference:
    - https://google.com

matchers-condition: and
matchers:
  - type: word
    patterns:
      - abcd
      - dddd
    condition: and

  - type: regex
    patterns:
      - ".*"
      - "^a"
    condition: or

category: secret
techs:
  - *
  - ruby-rails
```

## Flow

```mermaid
graph TD
    A[Load Rule File] --> B[Validate Rules]
    B --> C[Check Issues using Rules in Detector]
    C -->|Issue Detected| D[Store in Passive Scan Results]
    C -->|No Issue| E[Proceed]
    D --> F[Continue with Other Processes]
    E --> F
    F --> G[Generate Output]
    G --> H[Include Passive Scan Results in Output]
```
