### ISSUE TITLE
Add Support for ZAP Sites Tree Format in Output Options

### ISSUE THREAD

**Issue by hahwul** [owasp-noir/noir#482]
https://www.zaproxy.org/docs/desktop/addons/import-export/sitestreeformat/ (YAML)

```yaml
 - node:              # The name of the node, as shown in the ZAP Sites Tree
    url:               # The URL it represents, present for all apart from the top node
    method:            # The HTTP method, present for all apart from the top node
    responseLength:    # The length of the response, where relevant
    statusCode:        # The HTTP status code, where relevant
    data:              # The names of the data parameters, if any, separated with '=&'s
    children:          # A list of child nodes, present for all nodes apart from the leaves
```

Example

```yaml
- node: Sites
  children:
  - node: https://www.hahwul.com
    url: https://www.hahwul.com
    method: GET
    responseLength: 58064
    statusCode: 200
    children:
    - node: about
      url: https://www.hahwul.com/about
      method: GET
      children:
      - node: GET:/
        url: https://www.hahwul.com/about/
        method: GET
        responseLength: 60842
        statusCode: 200
      - node: POST:/()(1)
        url: https://www.hahwul.com/about/
        method: POST
        responseLength: 485
        statusCode: 405
        data: 1=
    - node: projects
      url: https://www.hahwul.com/projects
      method: GET
      children:
      - node: GET:/
        url: https://www.hahwul.com/projects/
        method: GET
        responseLength: 65654
        statusCode: 200
```
